### ISSUE TITLE
update to latest JOSM

### ISSUE THREAD

**Issue by don-vip** [kolesar-andras/josm-plugin-improve-way#1]
With Java 8 switch, plugin needs to be updated, see https://josm.openstreetmap.de/ticket/13356

**Comment by don-vip** [comment]
We've got another report (https://josm.openstreetmap.de/ticket/13511) can you please update the plugin?

**Comment by don-vip** [comment]
Would you be ok to transfer the repository to @JOSM organization so we can maintain the plugin?

**Comment by kolesar-andras** [comment]
Thank you, I will not have time for this in the near future.

**Comment by don-vip** [comment]
Thanks! I have promoted you team maintainer of https://github.com/orgs/JOSM/teams/improve-way can you please proceed to repo transfer ?

**Comment by don-vip** [comment]
Can you please transfer the repo, so we can update the plugin and fix our plugin integration tests? Thanks.

**Comment by don-vip** [comment]
repo forked :(
